apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: api-gateway-environment-secrets
data:
  OKTA_CLIENT_SECRET: "{{ required "okta.clientSecret is required and cannot be empty" .Values.okta.clientSecret | b64enc }}"
