apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-environment-secret-mongodb
data:
  MONGODB_URI: "{{ required "mongodbUri is required and cannot be empty" .Values.mongodbUri | b64enc }}"
