{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      serviceAccountName: "gke-nodes-kubernetes-service-account"
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.imageRepository }}/{{ .image }}:{{ .version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .port }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if .path }}
  name: {{ .name }}-load-balancer
  {{- else }}
  name: {{ .name }}-service
  {{- end }}
spec:
  {{- if .path }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .port }}
---
{{- end }}