{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      serviceAccountName: "kubernetes-apps-sa"
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.imageRepository }}/{{ .image }}:{{ .version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .port }}
          envFrom:
            - secretRef:
                name: app-environment-secret-mongodb
            - configMapRef:
                name: app-environment-gcp-project
            - configMapRef:
                name: app-environment-service-uris
            {{- if and .configs (gt (len .configs) 0) }}
            {{- range .configs }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if and .secretConfigs (gt (len .secretConfigs) 0) }}
            {{- range .secretConfigs }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
          env:
            - name: PUBSUB_TOPIC
              value: "{{ .name }}"
            - name: MONGODB_DB
              value: "{{ .name }}"
---
{{- if .path }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .name }}
  ports:
    - port: 80
      targetPort: {{ .port }}
      protocol: TCP
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .port }}
{{- end }}
---
{{- end }}