{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      serviceAccountName: "gke-nodes-kubernetes-service-account"
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.imageRepository }}/{{ .image }}:{{ .version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .port }}
          env:
            - name: GCP_PROJECT
              value: {{ $.Values.gcpProject | quote }}
            - name: MONGODB_URI
              value: {{ $.Values.mongodbUri | quote }}
            - name: PUBSUB_TOPIC
              value: {{ .name | quote }}
            - name: MONGODB_DB
              value: {{ .name | quote }}
---
{{- if .path }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .name }}
  ports:
    - port: 80
      targetPort: {{ .port }}
      protocol: TCP
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .port }}
{{- end }}
---
{{- end }}