namespace: autoinvestor

public_app:
  name: frontend
  image: docker.io/polpinol98/autoinvestor-frontend
  version: 0.0.2
  port: 8080

backends:
  - name: users
    image: docker.io/polpinol98/autoinvestor-users
    version: 0.0.5
    port: 8081
