imageRepository: europe-west3-docker.pkg.dev/autoinvestor-tfm/docker-images
domain: autoinvestor.alvaromanoso.dev
gcpProject: ""
mongodbUri: ""

okta:
  domain: "dev-20214328.okta.com"
  clientId: "0oaop5ffwazcO5OoV5d7"
  clientSecret: ""

apps:
  - name: users
    image: autoinvestor-users
    version: 2.12.0
    port: 8080

  - name: alerts
    image: autoinvestor-alerts
    version: 0.3.11
    port: 8080

  - name: portfolio
    image: autoinvestor-portfolio
    version: 2.0.0
    port: 8080

  - name: market-feeling
    image: autoinvestor-market-feeling
    version: 1.0.16
    port: 8080

  - name: news-scraper
    image: autoinvestor-news-scraper
    version: 0.0.2
    port: 8080

  - name: decision-making
    image: autoinvestor-decision-making
    version: 0.3.19
    port: 8080

  - name: core
    image: autoinvestor-core
    version: 2.0.11
    port: 8080

  - name: frontend
    image: autoinvestor-frontend
    version: 0.10.0
    port: 80
    path: /

  - name: api-gateway
    image: autoinvestor-api-gateway
    version: 2.32.1
    port: 8080
    path: /api