imageRepository: europe-west3-docker.pkg.dev/autoinvestor-tfm/docker-images
domain: autoinvestor.alvaromanoso.dev
gcpProject: ""
mongodbUri: ""

okta:
  resourceUri: "https://dev-20214328.okta.com/oauth2/default"
  clientId: "0oaop5ffwazcO5OoV5d7"
  clientSecret: ""

apps:
  - name: users
    image: autoinvestor-users
    version: 2.10.5
    port: 8080

  - name: alerts
    image: autoinvestor-alerts
    version: 0.3.6
    port: 8080

  - name: portfolio
    image: autoinvestor-portfolio
    version: 0.2.3
    port: 8080

  - name: market-feeling
    image: autoinvestor-market-feeling
    version: 1.0.5
    port: 8080
    configs:
      - market-feeling-environment

  - name: decision-making
    image: autoinvestor-decision-making
    version: 0.3.2
    port: 8080

  - name: core
    image: autoinvestor-core
    version: 2.0.2
    port: 8080
    configs:
      - core-environment

  - name: frontend
    image: autoinvestor-frontend
    version: 0.8.1
    port: 80
    path: /

  - name: api-gateway
    image: autoinvestor-api-gateway
    version: 2.29.1
    port: 8080
    path: /api
    configs:
      - api-gateway-environment
    secretConfigs:
      - api-gateway-environment-secrets