imageRepository: europe-west3-docker.pkg.dev/autoinvestor-tfm/docker-images
domain: autoinvestor.alvaromanoso.dev
gcpProject: ""
mongodbUri: ""

apps:
  - name: users
    image: autoinvestor-users
    version: 2.10.0
    port: 8080

  - name: alerts
    image: autoinvestor-alerts
    version: 0.3.6
    port: 8080

  - name: portfolio
    image: autoinvestor-portfolio
    version: 0.2.3
    port: 8080

  - name: market-feeling
    image: autoinvestor-market-feeling
    version: 1.0.2
    port: 8080

  - name: decision-making
    image: autoinvestor-decision-making
    version: 0.3.2
    port: 8080

  - name: core
    image: autoinvestor-core
    version: 2.0.2
    port: 8080
    configs:
      - core-environment

  - name: frontend
    image: autoinvestor-frontend
    version: 0.6.6
    port: 80
    path: /

  - name: api-gateway
    image: autoinvestor-api-gateway
    version: 2.27.0
    port: 8080
    path: /api
    configs:
      - api-gateway-environment
