imageRepository: docker.io/polpinol98
domain: autoinvestor.alvaromanoso.dev
gcpProject: ""
mongodbUri: ""

apps:
  - name: users
    image: autoinvestor-users
    version: 2.6.0
    port: 8080

  - name: alerts
    image: autoinvestor-alerts
    version: 0.3.4
    port: 8080

  - name: portfolio
    image: autoinvestor-portfolio
    version: 0.2.1
    port: 8080

  - name: market-feeling
    image: autoinvestor-market-feeling
    version: 0.2.9
    port: 8080

  - name: decision-making
    image: autoinvestor-decision-making
    version: 0.3.0
    port: 8080

  - name: core
    image: autoinvestor-core
    version: 1.1.0
    port: 8080

  - name: frontend
    image: autoinvestor-frontend
    version: 0.5.0
    port: 80
    path: /

  - name: api-gateway
    image: autoinvestor-api-gateway
    version: 2.17.0
    port: 8080
    path: /api
