name: Deploy

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths:
      - helm/**
  push:
    branches:
      - main
    paths:
      - helm/**
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ needs.e2e-test.outputs.namespace }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          install_components: 'kubectl'

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ vars.GCP_GKE_CLUSTER_NAME }}
          location: ${{ vars.GCP_GKE_CLUSTER_ZONE }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Build secret override
        run: |
          cat <<EOF > secret-values.yaml
          gcpProject: "${{ vars.GCP_PROJECT_ID }}"
          mongodbUri: "${{ secrets.MONGODB_URI }}"
          EOF

      - name: Deploy all to GKE (dry run)
        run: |
          helm upgrade --install autoinvestor ./helm \
            --namespace autoinvestor \
            --create-namespace \
            --force \
            --dry-run \
            -f secret-values.yaml

      - name: Deploy all to GKE
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          helm upgrade --install autoinvestor ./helm \
            --namespace autoinvestor \
            --create-namespace \
            --force \
            -f secret-values.yaml
