name: Deploy

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths:
      - helm/**
  push:
    branches:
      - main
    paths:
      - helm/**
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      HELM_REPO: "oci://${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/helm-charts"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          install_components: 'kubectl'

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ vars.GCP_GKE_CLUSTER_NAME }}
          location: ${{ vars.GCP_GKE_CLUSTER_ZONE }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Login to Artifact Registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' | helm registry login ${{ vars.GCP_REGION }}-docker.pkg.dev \
            --username=_json_key \
            --password-stdin

      - name: Build secret override
        run: |
          cat <<EOF > secret-values.yaml
          gcpProject: "${{ vars.GCP_PROJECT_ID }}"
          mongodbUri: "${{ secrets.MONGODB_URI }}"
          EOF

      - name: Deploy all to GKE (dry run)
        if: github.event_name == 'pull_request'
        run: |
          helm upgrade --install autoinvestor ./helm \
            --namespace autoinvestor \
            --create-namespace \
            --force \
            --dry-run \
            -f secret-values.yaml

      - name: Push to registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          cd helm
          current_version=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\)/\1/p' Chart.yaml)
          
          helm package .
          helm push "autoinvestor-${current_version}.tgz" "${HELM_REPO}"

      - name: Deploy all to GKE
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          current_version=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\)/\1/p' helm/Chart.yaml)
          
          helm pull "${HELM_REPO}/autoinvestor" --version "${current_version}"

          helm upgrade --install autoinvestor "autoinvestor-${current_version}.tgz" \
            --namespace autoinvestor \
            --create-namespace \
            --version "${current_version}" \
            -f secret-values.yaml
